project:
  type: website
  output-dir: docs
  resources:
    - resume.pdf
    - V_Pletsch_CV.pdf

website:
  title: "Homepage"
  navbar:
    background: transparent
    search: true
    right:
      - text: "Projects"
        href: projects.qmd
      - text: "Resume"
        href: experience.qmd
      - text: "Writing Samples"
        href: writingsamplese.qmd
      - text: "Contact"
        href: contact.qmd
    
  page-footer:
    left: "<div id='footer'></div>"
    right:
      - icon: github
        href: https://github.com/vmpletsch
      - icon: linkedin
        href: http://linkedin.com/in/veronica-pletsch-a49331100
      - icon: envelope
        href: vmpletsch@gmail.com

format:
  html:
    embed-resources: true
    theme: cosmo
    css: 
      - custom.css
    toc: true
    toc-location: left
    google-fonts:
      - family: Fraunces
      - family: Montserrat
      - family: DM Serif Display
